/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

public class FindtheDifferences
{
    public char FindTheDifference(string s, string t)
    {
        long sum = 0;
        for (int i = 0; i < t.Length; i++)
        {
            sum += t[i] - '0';
        }
        for (int i = 0; i < s.Length; i++)
        {
            sum -= s[i] - '0';
        }
        return (char)(sum + '0');
    }
}